### ISSUE TITLE
Does not recognize `break-word` value of `word-break`

### ISSUE THREAD

**Issue by cvrebert** [w3c/css-validator#128]
Spec: https://www.w3.org/TR/css-text-3/#valdef-word-break-break-word

Example input:
```css
#foo {
  word-break: break-word;
}
```

Output from validator:
> #foo | break-word is not a word-break value : break-word
