### ISSUE TITLE
Add support for the `background-position-x` and `background-position-y` properties

### ISSUE THREAD

**Issue by Arttse** [w3c/css-validator#149]
The [background-position-x](https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-x) and [background-position-y](https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-y) properties are used for a very long time, which [supported in 94.36% browsers](https://caniuse.com/#feat=background-position-x-y).

---

For now with this example
```css
.example {
  background-position-x: center;
  background-position-y: center;
}
```
validator with preset `CSS level 3 + SVG` says:
```
2 | .example | Property background-position-x doesn't exist : center
3 | .example | Property background-position-y doesn't exist : center
```
