### ISSUE TITLE
<basic-shape> values of `clip-path` property aren't recognized

### ISSUE THREAD

**Issue by cvrebert** [w3c/css-validator#150]
Example:
```css
#foo {
  clip-path: inset(50%);
}
```

Result:
> `inset(50%)` is not a `clip-path` value : `inset(50%)`

* Spec for `clip-path`: https://www.w3.org/TR/css-masking-1/#the-clip-path
* Spec for `<basic-shape>`: https://www.w3.org/TR/css-shapes/#supported-basic-shapes
