### ISSUE TITLE
"Validated CSS" is not correct for some @​rules

### ISSUE THREAD

**Issue by ylafon** [w3c/css-validator#182]
Like `@media screen {
}`giving `@media screen` in the output, or improper `{` in the case of nested @​rules.

**Comment by hannibal218bc** [comment]
Consider this example:

```css
@media print {
    @page {size: a4}
    body {background: none}
 }```

The validator will currently show:
```css
@media print {}
@page {size: a4}
body {background: none}
```

Notice how the "@media print" is ended before the @page block and how the "body" rule is promoted to the global (unrestricted) level.

Is this also in the scope of this issue?
