### ISSUE TITLE
Parse errors on namespace prefixes

### ISSUE THREAD

**Issue by mthuurne** [w3c/css-validator#213]
Feed the following CSS fragment to the validator using the CSS level 3 profile:
```css
@namespace xlink "http://www.w3.org/1999/xlink";
a[xlink|href] { color: red; }
```
It will report a parse error on `[xlink|href]`. However, as far as I know the syntax is correct.

I also tried using a namespace on an element name instead of on an attribute name, but that also leads to a parse error.

The `@namespace` rule is parsed without problems, so there is some kind of namespace support in the parser.
