### ISSUE TITLE
Please ignore non-existing pseudo-class on pseudo-element vendor extension

### ISSUE THREAD

**Issue by mthuurne** [w3c/css-validator#214]
Validate the following fragment while treating vendor extensions as warnings:
```css
::-webkit-scrollbar:vertical {
	border: 1px solid black;
}
```
The validator will report the `::-webkit-scrollbar` pseudo-element vendor extension as a warning, as expected. However, it reports the `:vertical` pseudo-class as an error. Maybe that is formally correct, but from a practical point of view, I would very much prefer if `vertical` would be ignored because it applies to a vendor extension.
