### ISSUE TITLE
rgba(r,g,b,a) is rewritten to new rbg(r,g,b / a) syntax

### ISSUE THREAD

**Issue by hannibal218bc** [w3c/css-validator#257]
Apparently starting with b88f463f2427135a7f914ff63c78120e7471f119 , the output of RGBA.toString() with a CSS3 profile is now formatted with the new CSS-color-4 syntax of `rgb(r,g,b / a)` (notice the slash between 3rd and 4th argument).

Example Input:
```css
@media    screen   and   (min-width: 400px){
 * {color: rgba(60, 120, 180, 0.5);}
} 
```

Example Output:
```css
@media screen and (min-width: 400px) {
* {color : rgb(60 120 180 / 0.5);}
} 
```

The problem is: IE / Edge seem to not fully support this new syntax, so when you use the "validated stylesheet" as output by the validator, any rgba() color will not be displayed correctly on those browsers.

I've forked the project and reverted to using rgb/rgba with "comma" arguments.

I guess the change to using `rgb()` with the "slash" notation was intentional, but was it perhaps a bit too early?
