### ISSUE TITLE
Multiple values for font-weight inside @font-face

### ISSUE THREAD

**Issue by fanich37** [w3c/css-validator#262]
According to MDN the modern browsers do support up to two values. And CSS-validator kinda agreed with such a statement and it doesn't complain about it.
But for the input:
```css
@font-face {
  font-weight: 400 700;
}
```
In the ```Valid CSS information``` section i've got output:
```css
@font-face {
  font-weight : 400;
}
```
So it tells that css is correct however the second value is lost :confused: Is it correct behaviour?
