### ISSUE TITLE
Properties are copied to empty @page block

### ISSUE THREAD

**Issue by hannibal218bc** [w3c/css-validator#267]
Consider this example:
```CSS
H1 {color: red}
@page { }
```

The validator accepts that, but the output is:
```CSS
H1 {
color : red;
}
@page {
{
color : red;
}
}
```

As you can see, the "color" property from the H1 is copied to the @page block. It seems that other @-Rules (media, viewport, font-face) do not exhibit this behaviour.
