### ISSUE TITLE
Accept color-adjust

### ISSUE THREAD

**Issue by oliviertassinari** [w3c/css-validator#276]
The validator rejects

```css
.foo {
  color-adjust: exact;
}
```

However, this CSS property seems to be on its way to standardization:

- https://www.w3.org/TR/css-color-adjust-1/#perf
- https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust
