### ISSUE TITLE
Problems with colors defined as variables for "fill" property

### ISSUE THREAD

**Issue by PiotrSss** [w3c/css-validator#336]
For example:

```css
:root {
    --el-clr: #000;
}
.el {
    fill: var(--el-clr);
}
```

generates error: `var(--el-clr)` is not a valid color 3 or 6 hexadecimals numbers : `var(--el-clr)`
