### ISSUE TITLE
`place-self` values: `center`, `flex-start`, `flex-end`

### ISSUE THREAD

**Issue by eriknicholas** [w3c/css-validator#338]
Upon checking my Grid layout's CSS, the validator reported the values `center`, `flex-start`, `flex-end` are invalid for the property `place-self`.

My CSS was:
```css
    .classA{ place-self: stretch center }
    .classB{ place-self: stretch flex-start }
    .classC{ place-self: stretch flex-end }
```
Apologies if I'm completely wrong here. I could be in the wrong place (I believed this the place to report issues with the online W3C CSS Validation Service, but maybe it's not), or I may be reporting the wrong thing (maybe my understanding of `place-self` is super flawed), or I could even be too early to report this (while it may be "supported" by every browser, it may not be "official spec" yet, I'm still learning, but trying to be helpful.)
