### ISSUE TITLE
Bug on @font-face unicode-range

### ISSUE THREAD

**Issue by jfoclpf** [w3c/css-validator#350]
This seems to be a bug on your validator since there is no reason to reject this type of `unicode-range`s

```css
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 400;
  src: local('Nunito Regular'), local('Nunito-Regular'), url("fonts/XRXV3I6Li01BKofINeaB.woff2") format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  font-display: fallback;
}
```

Please do kindly check why this seems to be a bug: https://stackoverflow.com/a/69711789/1243247
