### ISSUE TITLE
Support `@support selector()`

### ISSUE THREAD

**Issue by Seirdy** [w3c/css-validator#361]
The `@supports` at-rule now supports the `selector()` function [as of CSS conditionals level 4](https://www.w3.org/TR/css-conditional-4/#at-supports-ext).

Safari, Chromium, Edge, and Firefox have shipped support. The CSS validator and Nu validator fail to parse it.

Contrived test-case:

``` css
@supports selector(:focus) {
	code {
		display: inherit
	}
}
```

Real-world test-case: the `<style>` element for https://seirdy.one/
