### ISSUE TITLE
Support `prefers-contrast: less`

### ISSUE THREAD

**Issue by Seirdy** [w3c/css-validator#363]
The CSS validator currently marks `less` as an invalid value for `prefers-contrast`. [The Media Queries Level 5 specification](https://www.w3.org/TR/mediaqueries-5/#descdef-media-prefers-contrast) currently lists the `less` value as valid. Chromium DevTools support testing the feature.

Contrived test-case:

``` css
@media (prefers-contrast: less) {
  html {
    background-color: #ddd;
  }
}
```

Real-world test-case: the `<style>` element for https://seirdy.one/
