### ISSUE TITLE
Image-set

### ISSUE THREAD

**Issue by KevinGIRAULT** [w3c/css-validator#388]
Hello,

The image-set property is not recognized by w3c Jigsaw validator. Here is an example from MDN image-set page:

```css
.box {
  background-image: -webkit-image-set(
    url("small-balloons.jpg") 1x,
    url("large-balloons.jpg") 2x);
  background-image: image-set(
    url("small-balloons.jpg") 1x,
    url("large-balloons.jpg") 2x);
}
```
The validator seems to recognize only the -webkit version.

Source : https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set

**Comment by Raccffy** [comment]
This is still an issue in the latest version of CSS Validator, vnu and [Nu Html Checker](https://validator.w3.org/nu/).

## Source CSS

["Using image-set() to provide alternative background-image options"](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/image/image-set#using_image-set_to_provide_alternative_background-image_options)

```css
.box {
  width: 400px;
  height: 200px;
  background-repeat: no-repeat;
  background-size: cover;

  background-image: image-set(
    url("https://mdn.github.io/shared-assets/images/examples/balloons-small.jpg")
      1x,
    url("https://mdn.github.io/shared-assets/images/examples/balloons-landscape.jpg")
      2x
  );
}
```

## Tested Environments

### CSS Validator (This repository)

- css-validator: `cssval-20250226`
- Java: `Eclipse Adoptium JDK 17.0.9.9`

```
{output=text, profile=css3svg, vextwarning=true, warning=2, medium=all, lang=en}
W3C CSS Validator results for http://localhost/test.css


Sorry! We found the following errors (1)


URI : http://localhost/test.css

Line : 12 .box
       (Value Error : background-image (nullcolors.html#propdef-background-image))
       “image-set(url("https://mdn.github.io/shared-assets/images/examples/balloons-small.jpg") 1x,url("https://mdn.github.io/shared-assets/images/examples/balloons-landscape.jpg") 2x)” is not a “background-image” value :



Valid CSS information
```

### vnu

- vnu: `26.4.2 (8511a6e)`
- Java: `Eclipse Adoptium JDK 17.0.9.9`

vnu result:
```
"file:/---/example.css":12.3-12.3: error: CSS: “background-image”: “image-set(url("https://mdn.github.io/shared-assets/images/examples/balloons-small.jpg") 1x,url("https://mdn.github.io/shared-assets/images/examples/balloons-landscape.jpg") 2x)” is not a “background-image” value.
```

### [Nu Html Checker](https://validator.w3.org/nu/)

- vnu: `26.4.1`

<img width="1280" height="840" alt="Image" src="https://github.com/user-attachments/assets/d389c2ae-40ac-4d9e-aba1-028b27cd2410" />
