### ISSUE TITLE
Unrecognized at-rule "@layer"

### ISSUE THREAD

**Issue by vrugtehagel** [w3c/css-validator#410]
Essentially, the title says it all. The `@layer` rule has been part of the CSS specs for quite a while and is supported by all major browsers. I believe it should not fail validation.

Here is an example that fails saying "Unrecognized at-rule `@layer`":

```css
@layer foo {
  div {
    color: red;
  }
}
```

Also, the declaration-only version fails in the same way:

```css
@layer foo, bar;
```
