### ISSUE TITLE
CSS variable in clamp() without default value

### ISSUE THREAD

**Issue by kamenf** [w3c/css-validator#412]
When using CSS variable without default value in clamp() reports "The types are incompatible" error.

Example:
```css
.my-class {
  font-size: clamp(0.5rem, var(--outer-size) / 7.5, 2rem);
}
```
generates:

```
Value Error : font-size The types are incompatible )
```
