### ISSUE TITLE
`filter: invert()` is invalid

### ISSUE THREAD

**Issue by MajliTech** [w3c/css-validator#413]
Somehow, [despite being documented](https://developer.mozilla.org/en-US/docs/Web/CSS/filter), `filter: invert()` in my CSS is not valid. 
```
$ java -jar css-validator.jar file://$HOME/Downloads/css.css
{output=text, profile=css3svg, vextwarning=true, warning=2, medium=all, lang=en}
W3C CSS Validator results for file:/home/majlitech/Downloads/css.css


Sorry! We found the following errors (1)


URI : file:/home/majlitech/Downloads/css.css

Line : 25 .pb-45 > a > img
       Parse Error
       invert()



Valid CSS information

    *
    {
        color : black  !important ;
    }
    .p-80
    {
        background : none ;
    }
    .p-80 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(1)
    {
        background : white ;
    }
    .p-15
    {
        background : #f2f2f2 ;
    }
    .td > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2), .p-80 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(13), .p-80 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(14)
    {
        display : none ;
    }
```
### `css.css`
```css
/*            Some CSS: https://github.com/MajliTech/some-css            */
/*                     Copyright (C) 2024 MajliTech                      */
/*                                                                       */
/* This program is free software: you can redistribute it and/or modify  */
/* it under the terms of the GNU General Public License as published by  */
/*   the Free Software Foundation, either version 3 of the License, or   */
/*                  (at your option) any later version.                  */
/*    This program is distributed in the hope that it will be useful,    */
/*    but WITHOUT ANY WARRANTY; without even the implied warranty of     */
/*     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the     */
/*             GNU General Public License for more details.              */
/*   You should have received a copy of the GNU General Public License   */
/* along with this program.  If not, see <https://www.gnu.org/licenses/>. */

/* You can inject this file into a Steam Receipt, which you will show on https://store.steampowered.com/account/receipt/<purchase id> */
/* This will make the receipt printable, so it uses less ink.                                                                         */

* {
  color: black !important;
}
.p-80 {
  background: none;
}
.pb-45 > a > img {
  filter: invert();
}
.p-80 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(1) {
  background: white;
}
.p-80 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(6) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) {
  
}
.p-15 {
  background: #f2f2f2;
}
.td > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2), .p-80 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(13), .p-80 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > table:nth-child(14) {
  display: none
}


```
