### ISSUE TITLE
font-optical-sizing isn't a property 

### ISSUE THREAD

**Issue by Banaanae** [w3c/css-validator#425]
```css
.class {
    font-optical-sizing: auto;
}
```
```
Error: font-optical-sizing: Property font-optical-sizing doesn't exist.
```
https://developer.mozilla.org/en-US/docs/Web/CSS/font-optical-sizing
