### ISSUE TITLE
`color-mix` causes value error

### ISSUE THREAD

**Issue by clemeth** [w3c/css-validator#434]
The `color-mix` functional notation is supported by all major browsers, but the validator does not recognize it.

So far, I have encountered errors like the following:

> Value Error : color `in` is not a `color` value : `color-mix(in srgb,blue,green)`

Input:

```css
.foo {
  color: color-mix(in srgb, blue, green);
}
```
