### ISSUE TITLE
oklch() function is not recognized

### ISSUE THREAD

**Issue by scalisi** [w3c/css-validator#436]
I tried to validate the following CSS (copied from [here](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/relative-currentcolor-oklch-01.html)), which includes the [oklch() function](https://drafts.csswg.org/css-color-5/#funcdef-oklch):

```css
div {
  width: 100px;
  height: 100px;
  background-color: red;
  color: red;
  background-color: oklch(from currentColor l c h);
}
```

I received the following error:

`Value Error : background-color oklch(from currentColor l c h) is not a background-color value : oklch(from currentColor l c h)`

[vnu](https://github.com/validator/validator) has the [same issue](https://github.com/validator/validator/issues/1725).

**Comment by VioletPixel** [comment]
I also ran into this issue, but I initially thought the validator was having a problem with CSS variables because of the way the error manifested.

If you try to validate the following CSS:

```css
:root {
  --lightness: 50%;
}

html {
  color: oklch(var(--lightness) 50% 270);
}
```

The error returned is:

> Value Error : color `var(--lightness)` is not a `color` value : `oklch(var(--lightness) 50% 270)`

The fact that it called out `var(--lightness)` specifically had me searching for issues about CSS variables instead of the true culprit, which is the lack of support for the `oklch()` function.
