### ISSUE TITLE
Validator seems to process only one level of CSS 3 rules

### ISSUE THREAD

**Issue by bluecat76** [w3c/css-validator#44]
# Following valid ruleset yields errors:

``` css
@media (min-width: 992px) and (max-width: 1199px) {
  #foo {
    position:absolute;
    animation: foobar 5s ease-in-out infinite alternate;
  }

@keyframes foobar {
    0% {
        transform: scale(1.0);
    }
    100% {
        transform: scale(2.0);
    }
  }
}
```
# Errors:

**W3C CSS Validator results for TextArea (CSS level 3)**
Sorry! We found the following errors (2)
URI : TextArea
17      Parse Error @keyframes foobar { 0% { transform: scale(1.0); } 100% { transform: scale(2.0); } }
18      Parse Error } 
## There are no errors when parsing one of the following CSS inputs alone:

``` css
@media (min-width: 992px) and (max-width: 1199px) {
  #foo {
    position:absolute;
    animation: foobar 5s ease-in-out infinite alternate;
  }
}
```

``` css
@keyframes foobar {
    0% {
        transform: scale(1.0);
    }
    100% {
        transform: scale(2.0);
    }
  }
```
