### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by boris-petrov** [w3c/css-validator#445]
```css
::highlight(a),
::highlight(b),
::highlight(c) {
  background-color: yellow;
  color: black;
}
```

I get three times `Error: CSS: Parse Error.` on the three `::highlight` lines. I think that's a bug in the CSS-validator.
