### ISSUE TITLE
CSS level 3 + SVG profile throws errors “#<hex> is not a fill/stroke value”, but code looks right (?)

### ISSUE THREAD

**Issue by tripu** [w3c/css-validator#59]
When validating [`w3.org/TR/2016/CR-secure-contexts-20160915`](https://www.w3.org/TR/2016/CR-secure-contexts-20160915/) with profile *CSS level 3 + SVG*, the validator complains: [“#<hex> is not a fill/stroke value”](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FCR-secure-contexts-20160915%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en) four times.

The offending chunk seems to be:

```css
.secure {
  fill: #88FF88;
}
.non-secure {
  fill: #FF8888;
  stroke-dasharray: 5px, 5px;
}
text.rejection {
  fill: #FF0000;
  font-weight: 700;
  font-size: 2em;
}
g path {
  stroke-width: 2;
  stroke: #666666;
  fill-opacity: 0;
  stroke-dasharray: 5px, 5px;
}
```
