### ISSUE TITLE
Bug: Nested Rules Are Unsupported

### ISSUE THREAD

**Issue by niedzielski** [w3c/css-validator#72]
Nested rules don't seem to validate correctly. Consider [the following example](https://www.w3.org/TR/css3-conditional/#processing):

```css
@media print {
  /* hide navigation controls when printing */
  #navigation { display: none }
  @media (max-width: 12cm) {
    /* keep notes in flow when printing to narrow pages */
    .note { float: none }
  }
}
```

The [validator](https://jigsaw.w3.org/css-validator/validator) reports ambiguous errors:

```
7		Parse Error @media (max-width: 12cm) { /* keep notes in flow when printing to narrow pages */ .note { float: none } }
8		Parse Error }
```
